### ISSUE TITLE
Wrap the selected UI.

### ISSUE THREAD

**Issue by Westbrook** [samthor/advanced-input#1]
When the actual content of the textarea/input wraps, the selected UI doesn't not wrap with it. Here is the UI as displayed:

![image](https://user-images.githubusercontent.com/1156657/53677011-b19ad580-3c77-11e9-9e6d-fb7836f07ec4.png)

And the UI with the `_align` element highlighted in the elements tab to show how it doesn't wrap along with the textarea content;

![image](https://user-images.githubusercontent.com/1156657/53676999-9a5be800-3c77-11e9-8601-a09a6c8d58c6.png)

**Comment by samthor** [comment]
Fixed in a8e1799816d03a12c7147618b366178eb4613a45.
