### ISSUE TITLE
x-browser

### ISSUE THREAD

**Issue by Westbrook** [samthor/advanced-input#2]
The expereience delivered between FireFox and Chrome/Safari is not currently the same:

Firefox:
![image](https://user-images.githubusercontent.com/1156657/53677136-363a2380-3c79-11e9-96af-9f42f6b3565b.png)

Chrome/Safari:
![image](https://user-images.githubusercontent.com/1156657/53677141-3f2af500-3c79-11e9-9e7c-ae9eb5a286f8.png)

When applying the text content `I'd like to think about important things and the I'm confused.` and clicking into the word "about" you are delivered the above UIs.

**Comment by samthor** [comment]
This is fixed in 3c084c8f6c62f7e5ca5b39e1152b638a0c1a4f86.
